# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AQapN3Czzm_HUCYErvoACEjGoy0UCfEW
"""

#chatbot push to github >requirement txt connect to streamlit cloud and u can see online ur application

pip install streamlit

import streamlit as st
import random

# Page setup
st.set_page_config(page_title="Unique Chatbot", page_icon="🤖", layout="centered")
st.title("🤖 Friendly Chatbot")

# Keep chat history
if "messages" not in st.session_state:
    st.session_state["messages"] = []

# Predefined responses (adds uniqueness)
responses = {
    "hello": ["Hey there! 👋", "Hello! How’s your day going?", "Hi, glad you’re here!"],
    "how are you": ["I’m doing great, thanks! 🤖", "All circuits running fine ⚡", "Better now that we’re chatting!"],
    "bye": ["Goodbye! 👋 Take care!", "See you later!", "Bye! Come back soon!"],
    "joke": [
        "Why don’t robots ever get tired? Because they recharge! 🔋",
        "I told my computer a joke... but it didn’t get it 😅",
        "Beep boop! That’s robot for *haha* 🤖"
    ]
}

# Get reply function
def get_bot_reply(user_text):
    text = user_text.lower()

    for key in responses:
        if key in text:
            return random.choice(responses[key])

    return f"I’m not sure how to respond to '{user_text}', but I’m learning every day! 🚀"

# User input
user_input = st.chat_input("Type something...")

if user_input:
    # Add user message
    st.session_state["messages"].append({"role": "user", "content": user_input})

    # Generate bot reply
    bot_reply = get_bot_reply(user_input)

    # Add bot reply
    st.session_state["messages"].append({"role": "assistant", "content": bot_reply})

# Show messages
for msg in st.session_state["messages"]:
    st.chat_message(msg["role"]).markdown(msg["content"])

#nlppract2-ica2-pushing to chatbot